export * from "./Gallery/Gallery"
export * from "./CardCharacter/CardCharacter"
export * from "./Title/Title"
export * from "./SubTitle/SubTitle"
export * from "./Header/Header"
export * from "./Footer/Footer"
